<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Dalamud.NET.Sdk/15.0.0">
  <PropertyGroup>
    <Version>1.0.0.1</Version>
    <Title>TreasureForecast</Title>
    <Authors>TreasureForecast</Authors>
    <PackageProjectUrl>https://github.com/TreasureForecast/TreasureForecast</PackageProjectUrl>
    <PackageLicenseExpression>AGPL-3.0-or-later</PackageLicenseExpression>
    <IsPackable>false</IsPackable>
    <RootNamespace>TreasureForecast</RootNamespace>
    <AssemblyName>TreasureForecast</AssemblyName>
  </PropertyGroup>
</Project>
